### ISSUE TITLE
Best audio to text proportion

### ISSUE THREAD

**Issue by Vadim2S** [WangHelin1997/SoloAudio#8]
Now the training set concatenated from 1 my_real_audio_to_image CLAP and 3 other_model_text_to_mage CLAP generation. Why 1 real to 3 generated?

**Comment by WangHelin1997** [comment]
Hi! This is because we augment the text with three ways: (1) <class label> (2) "an audio clip of <class label>" (3) "the sound of <class label>".

It may look confusing so I just remove them and you can augment the text by yourself.

See [https://github.com/WangHelin1997/SoloAudio/blob/main/train.py](https://github.com/WangHelin1997/SoloAudio/blob/main/train.py).
